### ISSUE TITLE
MakeBlock needs to be stored and fetched from filestorage.

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#487]
https://github.com/razor-network/razor-go/blob/1af28821feec2acde384177bb188c504465b07bc/cmd/propose.go#L184

**Comment by ashish10677** [comment]
During commit, we store the data into a file and then when we reveal we pick up data from that saved file. We need a similar implementation for make block. We call make block during propose, and then call make block again during dispute. When we call make block during propose, at that time we can store the medians into a file and while disputing, instead of calling the same function again, we can use the median values stored in the file.
