### ISSUE TITLE
Dispute Fails

### ISSUE THREAD

**Issue by SkandaBhat** [razor-network/razor-go#718]
@Yashk767 Please add more details here.

**Comment by Yashk767** [comment]
> @Yashk767 Please add more details here.

Dispute is failing as same votes are getting appended to sortedVotes array for a collection which results in wrong calculation of total influence revealed.

With current implementations , 
e,g for collection 1 - votes are 100,100,101,100  //votes are in bigIntegers
so the sorted votes array becomes ,sortedVotes[] = {100,100,100,101}
Ideally it should be sortedVotes[] = {100,101}

This is happening as we have recently changed the data type of votes from uint32 to *big.Int in razor-go due to change in  votes data type from uint32 to uint256 in contracts
